[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-ign_mountain
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-ign_mountain
GtkTheme=oomox-ign_mountain
IconTheme=oomox-ign_mountain
MetacityTheme=oomox-ign_mountain
